### ISSUE TITLE
iOS8 bug

### ISSUE THREAD

**Issue by l1002k** [mangofever/UIAlertViewWithBlock#3]
when keyWindow.rootViewController.presetedController is not nil, alert can't show.
file BEAlertPresenter line 36

**Comment by mangofever** [comment]
Sorry about late reply.
I've took dayoffs for couple of days.

I'll check that.

Thanx.

**Comment by mangofever** [comment]
I think the issue was fixed at version 1.1.3.
@l1002k Could you please check your version?
